version: '2'
services:
 kex:
   build: components/KEX
   ports:
      - "20001:20001"
   volumes:
      - ./data/kex:/root/.kex 
  
 frontend:
   build: components/Frontend
#  environment:
#    - Frontend_FE_PASSWORD=tastamam
#  links:
#    - kex:kex
   ports:
      - "20000:20000" 
   volumes:
      - ./data/entrance:/root/.entrance
      - ./components/Frontend/config:/Entrance-PJ/Entrance-UM/src/config 
