version: '2'
services:
 kex:
   build: components/KEX
   ports:
     - "5001:5001"
   volumes:
      - "./data/kex:/root/.kex" 
  
 frontend:
   build: components/Frontend
#  environment:
#    - Frontend_FE_PASSWORD=tastamam
#  links:
#    - kex:kex
   ports:
      - "5000:5000" 
   volumes:
      - "./data/entrance:/root/.entrance"    
